#!/bin/sh
name=$1
SSDPV=/dev/mapper/cryptssd
VG=space

case $2 in
	on)
		lvcreate -n ${name}_cache -L 8G $VG $SSDPV
		lvcreate -n ${name}_cache_meta -L 16M $VG $SSDPV
		lvconvert -y --type cache-pool --poolmetadata $VG/${name}_cache_meta $VG/${name}_cache
		lvconvert -y --type cache --cachemode writeback --cachepool $VG/${name}_cache $VG/${name}
		;;
	off)
		lvconvert --splitcache $VG/${name}
		lvremove -y space/${name}_cache
		;;
	*)
		echo Current cached volumes:
		lvs -S 'lv_attr =~ ^C'
		echo invoke:
		echo "$0 volumename [off|on]"
esac
