#!/usr/bin/env python
import gnomekeyring
import errno
 
def main():
    for keyring in gnomekeyring.list_keyring_names_sync():
        for id in sorted(gnomekeyring.list_item_ids_sync(keyring)):
            try:
                item = gnomekeyring.item_get_info_sync(keyring, id)
                itemattr=gnomekeyring.item_get_attributes_sync(keyring,id)
                print '%d [%s] %s = %s : %s' % (
                    id, keyring, item.get_display_name(), itemattr['username_value'], item.get_secret())
            except (KeyError,):
                print '%d [%s] %s ERROR' % (
                    id, keyring, item.get_display_name())
            except (gnomekeyring.IOError,):
                pass
        else:
            if len(gnomekeyring.list_item_ids_sync(keyring)) == 0:
                print '[%s] --empty--' % keyring
 
if __name__ == '__main__':
    main()
