#!/usr/bin/python
import os.path
import sys
import time
try:
        pid=int(sys.argv[1])
        fd=int(sys.argv[2])
        if len(sys.argv)>2:
            fsize=int(sys.argv[3])
        else:
            fsize=os.path.getsize(pathfd)
        pathfdinfo="/proc/%d/fdinfo/%d" % (pid,fd)
        pathfd="/proc/%d/fd/%d" % (pid,fd)
except:
        print "bledne dane pid: %d fd: %d" % (pid,fd)
        sys.exit(1)
current=0
while(1):
        try:
                fdinfo=open(pathfdinfo,'r')
        except:
                print "Blad otwarcia pliku %s" % (path,)

        last=current
        current=int(fdinfo.readline().split("\t")[1])
        print current,fsize,100.0 * current/fsize,"ETA:", 10.0 * (fsize-current) / (current-last)
        time.sleep(10)
        fdinfo.close()
