#!/bin/sh
mine=LVDS2
xrandr --auto
xrandr --output DP1 --auto
xrandr --output DP2 --auto
xrandr --output DP3 --auto
xrandr --output VGA1 --auto
xrandr --output VGA2 --auto
xrandr --output LVDS1 --auto
xrandr --output HDMI1 --auto
xrandr --output HDMI2 --auto
xrandr --output HDMI3 --auto
xrandr --output LVDS2 --auto
xrandr --auto --output VGA1 --left-of $mine
xrandr --auto --output VGA2 --left-of $mine
xrandr --auto --output DP1 --right-of $mine
xrandr --auto --output DP2 --right-of $mine
xrandr --auto --output DP3 --left-of $mine
xrandr --auto --output HDMI1 --right-of $mine
xrandr --auto --output HDMI2 --right-of $mine
xrandr --auto --output HDMI3 --right-of $mine
if [ "$1" = "same" ]; then
	max=`xrandr  |awk '{print $1 }' |sort |uniq -c |grep "  2" |awk '{print $2}' |sort -n |tail -1`
	maxxx=1440x900
	xrandr  --output DP1 --mode $max
	xrandr  --output HDMI1 --mode $max
	xrandr  --output $mine --mode $max
	xrandr  --output VGA2 --mode $max
	xrandr --auto --output DP1 --same-as $mine
	xrandr --auto --output HDMI1 --same-as $mine
	xrandr --auto --output VGA2 --same-as $mine
elif [ "$1" = "off" ]; then
	xrandr --output DP1 --off
	xrandr --output VGA1 --off
	xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-0
fi
xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s auto
#xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s LVDS1
xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-1
#xrandr --auto --output DP1 --right-of LVDS1 --rotate right

setupeth()
{
	LC_ALL=C nmcli d list iface eth0 |grep GENERAL.CONNECTION |grep "not connected"
	isup=$?
	LC_ALL=C nmcli d list iface eth0 |grep CAPABILITIES.CARRIER-DETECT: |grep "yes"
	isconnected=$?
	echo isup: $isup isconnected: $isconnected
	if [ \( $isup = 0 \) -a \( $isconnected = 0 \) ]; then
		nmcli con up  uuid  ae86f034-c50e-4b44-aad5-5035e1ebed18
		sleep 10
		sudo /etc/init.d/openvpn restart
	fi
}

# 3 monitors
if [ "`xrandr -q |grep " connected" |wc -l`" -eq 3 ] ;then
setupeth
xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-1
xdotool search --class pidgin |while read id; do
	wmctrl -ir $id -b remove,maximized_vert,maximized_horz
	xdotool windowmove $id 0 25
	wmctrl -ir $id -b add,maximized_vert,maximized_horz
done
xdotool search --name Terminal |while read id; do
	wmctrl -ir $id -b remove,maximized_vert,maximized_horz
	#xdotool windowmove $id 1599 25
	xdotool windowmove $id 1920 49
	wmctrl -ir $id -b add,maximized_vert,maximized_horz
done
xdotool search --name chromium |while read id; do
	wmctrl -ir $id -b remove,maximized_vert,maximized_horz
	xdotool windowmove $id 3200 25
	wmctrl -ir $id -b add,maximized_vert,maximized_horz
done
fi

if [ "`xrandr -q |grep " connected" |wc -l`" -eq 1 ] ;then
#setupeth
	xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-0
fi

if [ "`xrandr -q |grep " connected" |wc -l`" -eq 2 ] ;then
#setupeth
	xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-0
fi

if [ "$1" = "off" ]; then
	xfconf-query -c xfce4-panel -p /panels/panel-0/output-name -s monitor-0
fi

synclient TouchpadOff=1 
